### ISSUE TITLE
Code tips

### ISSUE THREAD

**Issue by Chekushkin** [mtkachenk0/PayPalBusinessAccParser#1]
Suggest reading this one and apply everything you find there. https://github.com/bbatsov/ruby-style-guide
- Don't initialize a hash this way   
  ```ruby 
  {:"Account" => @account}
  ```
- Those redundant blank lines are so redundant.
- Using `protected` is unnecessary.
- Get rid of all those instance variables.
- Get rid of global variables.
- `rescue` is evil. Write your code the way you can avoid it.
- tripple evil
```ruby
def banana
  begin
    expression
  rescue
    one more expression
  ensure
    again an expression
    block do
      begin
        bla-bla-bla
      rescue
        oh my god im lost in those rescues
      ensure
        stop it really!
      end
    end
  end
end
```
- Do not override class String just to add one function. By the way such function already exists. 
```ruby
"love those rescues".is_a?(String)
=> true
```
- By the way
```ruby
money = if money_text[0][0].to_s.is_i?
  money_text[0]
elsif money_text[0][0].to_s.eql?('-')
  money_text[0].to_s[2..-1]
else
  money_text[0].to_s[1..-1]
end
```
- There are no blank lines where they are supposed to be.
- Indentation.
  NO!
  ```ruby
  @@myAcc = {:"Account" => @account,
            :"Balance" => @balance,
        :"Currency" => @currency}
  ```
  YES!
  ```ruby
  my_acc = {
    account:  @account,
    balance:  @balance,
    currency: @currency
  }
  ```
- Last function expression result is returned by default. No need to explicitly call ex.:   
`return @@myTransactions`
- Arguments naming should be more specific.
  NO!
  ```ruby
  def waiting(x)
  ```
  YES!
  ```ruby
  def waiting(element)
  ```

**Comment by mtkachenk0** [comment]
[Merged & closed](https://github.com/mtkachenk0/PayPalBusinessAccParser/pull/2)
